name: Continuous Delivery (CD)

on:
  workflow_run:
    workflows: ["Continuous Integration (CI)"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      # Verify code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Github connection
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build image and push for simple-api
      - name: Build and push API image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: true

      # Build and push image for database
      - name: Build and push Database image
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: true

      # Build and push image for httpd
      - name: Build and push HTTPD image
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: true